[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/livescore/*"
  to = "/.netlify/functions/livescore?path=/:splat"
  status = 200

[[redirects]]
  from = "/rss.xml"
  to = "/.netlify/functions/rss"
  status = 200

[[redirects]]
  from = "/feed.xml"
  to = "/.netlify/functions/rss"
  status = 200

[[redirects]]
  from = "/api/ls-cdn/*"
  to = "https://lsm-static-prod.livescore.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/ls-commentary/*"
  to = "https://prod-cdn-commentary-api.livescore.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
